### ISSUE TITLE
Suggestion to publish editable 3D-CAD data.

### ISSUE THREAD

**Issue by shiba-8ro** [AGIRobots/CyberGear-Additional-Reducer#1]
@AGIRobots I have started making PlanetaryGear-3.5xReducer, but I am having trouble with an issue specific to the 3D printer slicer software I am using. It depends on the resolution of the STL data. So I want to export the STL data at any resolution I want. Also, I would like to DfAM the data for better 3D printing results. Is it possible for you to publish the data in STEP format?
<img src="https://github.com/user-attachments/assets/24969abe-0c72-4892-b31c-c2ababb31493" width="300" >

**Comment by AGIRobots** [comment]
@shiba-8ro 
Thank you for your suggestion. I have added the data under the 3d_models folder as PlanetaryGear-3.5xReducer.step, please feel free to use it.

**Comment by shiba-8ro** [comment]
@AGIRobots 
Thank you. You shall close this issue.

**Comment by shiba-8ro** [comment]
@AGIRobots
Thank you. I closed this issue.
